version: '3.7'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public
    ports:
      - "80:80"
    depends_on:
      - laravel-app
      - mysql

  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./app:/var/www
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=testrentalcar  # Nom de la base de données
      - DB_USERNAME=root  # Nom de l'utilisateur
      - DB_PASSWORD=root_password  # Mot de passe de l'utilisateur
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Mot de passe pour l'utilisateur root
      MYSQL_DATABASE: testrentalcar  # Nom de la base de données
      MYSQL_USER: root  # Nom de l'utilisateur que vous avez créé
      MYSQL_PASSWORD: root_password  # Mot de passe pour l'utilisateur
    ports:
      - "3306:3306"

networks:
  default:
    external:
      name: nginx_network
